//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPIPositionProfit : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIPositionProfit(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIPositionProfit obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIPositionProfit() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPIPositionProfit(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string PositionNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_PositionNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_PositionNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint PositionStreamId {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_PositionStreamId_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_PositionStreamId_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double LMEPositionProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_LMEPositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_LMEPositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionMarketValue {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_OptionMarketValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_OptionMarketValue_get(swigCPtr);
      return ret;
    } 
  }

  public double CalculatePrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_CalculatePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_CalculatePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double FloatingPL {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_FloatingPL_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIPositionProfit_FloatingPL_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIPositionProfit() : this(TapTradeCppWrapperPINVOKE.new_TapAPIPositionProfit(), true) {
  }

}
