//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPIAccountRentInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIAccountRentInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIAccountRentInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIAccountRentInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPIAccountRentInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSource {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_MatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_MatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public char FeeMode {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_FeeMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_FeeMode_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenTurnover {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_OpenTurnover_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_OpenTurnover_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosedTurnover {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_ClosedTurnover_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_ClosedTurnover_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseNewTurnover {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CloseNewTurnover_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CloseNewTurnover_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenVolume {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_OpenVolume_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_OpenVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosedVolume {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_ClosedVolume_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_ClosedVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseNewVolume {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CloseNewVolume_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_CloseNewVolume_get(swigCPtr);
      return ret;
    } 
  }

  public char MarginMode {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_MarginMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_MarginMode_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyTInitMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyTInitMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyTInitMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellTInitMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellTInitMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellTInitMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyBInitMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyBInitMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyBInitMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellBInitMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellBInitMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellBInitMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyLInitMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyLInitMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyLInitMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellLInitMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellLInitMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellLInitMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyMInitMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyMInitMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyMInitMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellMInitMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellMInitMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellMInitMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyTMaintMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyTMaintMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyTMaintMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellTMaintMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellTMaintMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellTMaintMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyBMaintMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyBMaintMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyBMaintMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellBMaintMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellBMaintMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellBMaintMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyLMaintMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyLMaintMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyLMaintMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellLMaintMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellLMaintMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellLMaintMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyMMaintMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyMMaintMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_BuyMMaintMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellMMaintMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellMMaintMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountRentInfo_SellMMaintMargin_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIAccountRentInfo() : this(TapTradeCppWrapperPINVOKE.new_TapAPIAccountRentInfo(), true) {
  }

}
