//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CTACSharp.HS.Market {

public class CHSRspQryTradingAccountField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CHSRspQryTradingAccountField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CHSRspQryTradingAccountField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CHSRspQryTradingAccountField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HSMarketCppWrapperPINVOKE.delete_CHSRspQryTradingAccountField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountID {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_AccountID_set(swigCPtr, value);
    } 
    get {
      string ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_AccountID_get(swigCPtr);
      return ret;
    } 
  }

  public double YdBalance {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_YdBalance_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_YdBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double YdPositionMargin {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_YdPositionMargin_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_YdPositionMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double YdFundEquity {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_YdFundEquity_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_YdFundEquity_get(swigCPtr);
      return ret;
    } 
  }

  public double FundEquity {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FundEquity_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FundEquity_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionsMarketValue {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_OptionsMarketValue_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_OptionsMarketValue_get(swigCPtr);
      return ret;
    } 
  }

  public double Equity {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Equity_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Equity_get(swigCPtr);
      return ret;
    } 
  }

  public double AvailableBalance {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_AvailableBalance_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_AvailableBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double WithdrawBalance {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_WithdrawBalance_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_WithdrawBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double Margin {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Margin_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Margin_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenMargin {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FrozenMargin_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FrozenMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double RiskDegree {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_RiskDegree_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_RiskDegree_get(swigCPtr);
      return ret;
    } 
  }

  public double Premium {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Premium_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Premium_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenPremium {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FrozenPremium_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FrozenPremium_get(swigCPtr);
      return ret;
    } 
  }

  public double Commission {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Commission_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Commission_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenCommission {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FrozenCommission_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FrozenCommission_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfitByDate {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_CloseProfitByDate_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_CloseProfitByDate_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfitByDate {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_PositionProfitByDate_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_PositionProfitByDate_get(swigCPtr);
      return ret;
    } 
  }

  public double Deposit {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Deposit_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Deposit_get(swigCPtr);
      return ret;
    } 
  }

  public double Withdraw {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Withdraw_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_Withdraw_get(swigCPtr);
      return ret;
    } 
  }

  public double FundMortgage {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FundMortgage_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FundMortgage_get(swigCPtr);
      return ret;
    } 
  }

  public double WarrantMortgage {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_WarrantMortgage_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_WarrantMortgage_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenBalance {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FrozenBalance_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_FrozenBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double UnFrozenBalance {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_UnFrozenBalance_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryTradingAccountField_UnFrozenBalance_get(swigCPtr);
      return ret;
    } 
  }

  public CHSRspQryTradingAccountField() : this(HSMarketCppWrapperPINVOKE.new_CHSRspQryTradingAccountField(), true) {
  }

}

}
