//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CTACSharp.HS.Market {

public class CHSRspQryPositionField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CHSRspQryPositionField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CHSRspQryPositionField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CHSRspQryPositionField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HSMarketCppWrapperPINVOKE.delete_CHSRspQryPositionField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountID {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_AccountID_set(swigCPtr, value);
    } 
    get {
      string ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_AccountID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public char Direction {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_Direction_set(swigCPtr, value);
    } 
    get {
      char ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_Direction_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeType {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_HedgeType_set(swigCPtr, value);
    } 
    get {
      char ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_HedgeType_get(swigCPtr);
      return ret;
    } 
  }

  public double YdPositionVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_YdPositionVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_YdPositionVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double TodayPositionVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_TodayPositionVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_TodayPositionVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double AvailablePositionVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_AvailablePositionVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_AvailablePositionVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double TodayAvailablePositionVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_TodayAvailablePositionVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_TodayAvailablePositionVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionMargin {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionMargin_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double Premium {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_Premium_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_Premium_get(swigCPtr);
      return ret;
    } 
  }

  public double Commission {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_Commission_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_Commission_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_FrozenVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_FrozenVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double CombVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CombVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CombVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double CombFrozenVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CombFrozenVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CombFrozenVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double ExerciseFrozenVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_ExerciseFrozenVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_ExerciseFrozenVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenMargin {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_FrozenMargin_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_FrozenMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenPremium {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_FrozenPremium_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_FrozenPremium_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenCommission {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_FrozenCommission_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_FrozenCommission_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_OpenVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_OpenVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseVolume {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CloseVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CloseVolume_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenBalance {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_OpenBalance_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_OpenBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseBalance {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CloseBalance_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CloseBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionAveragePrice {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionAveragePrice_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionAveragePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionCost {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionCost_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionCost_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionAveragePriceByDate {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionAveragePriceByDate_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionAveragePriceByDate_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfitByDate {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionProfitByDate_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_PositionProfitByDate_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfitByDate {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CloseProfitByDate_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_CloseProfitByDate_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionsMarketValue {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_OptionsMarketValue_set(swigCPtr, value);
    } 
    get {
      double ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_OptionsMarketValue_get(swigCPtr);
      return ret;
    } 
  }

  public string UnderlyingInstrID {
    set {
      HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_UnderlyingInstrID_set(swigCPtr, value);
    } 
    get {
      string ret = HSMarketCppWrapperPINVOKE.CHSRspQryPositionField_UnderlyingInstrID_get(swigCPtr);
      return ret;
    } 
  }

  public CHSRspQryPositionField() : this(HSMarketCppWrapperPINVOKE.new_CHSRspQryPositionField(), true) {
  }

}

}
