//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CTACSharp.HS.Trade {

public class CHSExerciseField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CHSExerciseField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CHSExerciseField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CHSExerciseField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HSTradeCppWrapperPINVOKE.delete_CHSExerciseField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountID {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_AccountID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_AccountID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExerciseOrderSysID {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_ExerciseOrderSysID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_ExerciseOrderSysID_get(swigCPtr);
      return ret;
    } 
  }

  public int SessionID {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_SessionID_set(swigCPtr, value);
    } 
    get {
      int ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_SessionID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExerciseRef {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_ExerciseRef_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_ExerciseRef_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeType {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_HedgeType_set(swigCPtr, value);
    } 
    get {
      char ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_HedgeType_get(swigCPtr);
      return ret;
    } 
  }

  public char ExerciseType {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_ExerciseType_set(swigCPtr, value);
    } 
    get {
      char ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_ExerciseType_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderVolume {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_OrderVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_OrderVolume_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderStatus {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_OrderStatus_set(swigCPtr, value);
    } 
    get {
      char ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_OrderStatus_get(swigCPtr);
      return ret;
    } 
  }

  public int InsertDate {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_InsertDate_set(swigCPtr, value);
    } 
    get {
      int ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_InsertDate_get(swigCPtr);
      return ret;
    } 
  }

  public int InsertTime {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_InsertTime_set(swigCPtr, value);
    } 
    get {
      int ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_InsertTime_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorMsg {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_ErrorMsg_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_ErrorMsg_get(swigCPtr);
      return ret;
    } 
  }

  public string UnderlyingInstrID {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_UnderlyingInstrID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_UnderlyingInstrID_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      HSTradeCppWrapperPINVOKE.CHSExerciseField_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = HSTradeCppWrapperPINVOKE.CHSExerciseField_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public CHSExerciseField() : this(HSTradeCppWrapperPINVOKE.new_CHSExerciseField(), true) {
  }

}

}
