//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CTACSharp.HS.Trade {

public class CHSRspExerciseOrderInsertField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CHSRspExerciseOrderInsertField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CHSRspExerciseOrderInsertField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CHSRspExerciseOrderInsertField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HSTradeCppWrapperPINVOKE.delete_CHSRspExerciseOrderInsertField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountID {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_AccountID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_AccountID_get(swigCPtr);
      return ret;
    } 
  }

  public int SessionID {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_SessionID_set(swigCPtr, value);
    } 
    get {
      int ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_SessionID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExerciseOrderSysID {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_ExerciseOrderSysID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_ExerciseOrderSysID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExerciseRef {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_ExerciseRef_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_ExerciseRef_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderVolume {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_OrderVolume_set(swigCPtr, value);
    } 
    get {
      double ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_OrderVolume_get(swigCPtr);
      return ret;
    } 
  }

  public char ExerciseType {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_ExerciseType_set(swigCPtr, value);
    } 
    get {
      char ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_ExerciseType_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeType {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_HedgeType_set(swigCPtr, value);
    } 
    get {
      char ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_HedgeType_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderStatus {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_OrderStatus_set(swigCPtr, value);
    } 
    get {
      char ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_OrderStatus_get(swigCPtr);
      return ret;
    } 
  }

  public int InsertTime {
    set {
      HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_InsertTime_set(swigCPtr, value);
    } 
    get {
      int ret = HSTradeCppWrapperPINVOKE.CHSRspExerciseOrderInsertField_InsertTime_get(swigCPtr);
      return ret;
    } 
  }

  public CHSRspExerciseOrderInsertField() : this(HSTradeCppWrapperPINVOKE.new_CHSRspExerciseOrderInsertField(), true) {
  }

}

}
