//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcCFMMCBrokerKeyField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcCFMMCBrokerKeyField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcCFMMCBrokerKeyField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcCFMMCBrokerKeyField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPTradeCppWrapperPINVOKE.delete_CThostFtdcCFMMCBrokerKeyField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string BrokerID {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string ParticipantID {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_ParticipantID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_ParticipantID_get(swigCPtr);
      return ret;
    } 
  }

  public string CreateDate {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_CreateDate_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_CreateDate_get(swigCPtr);
      return ret;
    } 
  }

  public string CreateTime {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_CreateTime_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_CreateTime_get(swigCPtr);
      return ret;
    } 
  }

  public int KeyID {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_KeyID_set(swigCPtr, value);
    } 
    get {
      int ret = CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_KeyID_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrentKey {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_CurrentKey_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_CurrentKey_get(swigCPtr);
      return ret;
    } 
  }

  public char KeyKind {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_KeyKind_set(swigCPtr, value);
    } 
    get {
      char ret = CTPTradeCppWrapperPINVOKE.CThostFtdcCFMMCBrokerKeyField_KeyKind_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcCFMMCBrokerKeyField() : this(CTPTradeCppWrapperPINVOKE.new_CThostFtdcCFMMCBrokerKeyField(), true) {
  }

}
