//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcTradingNoticeInfoField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcTradingNoticeInfoField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcTradingNoticeInfoField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcTradingNoticeInfoField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPTradeCppWrapperPINVOKE.delete_CThostFtdcTradingNoticeInfoField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string BrokerID {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string SendTime {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_SendTime_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_SendTime_get(swigCPtr);
      return ret;
    } 
  }

  public string FieldContent {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_FieldContent_set(swigCPtr, value);
    } 
    get {
      string ret = CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_FieldContent_get(swigCPtr);
      return ret;
    } 
  }

  public short SequenceSeries {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_SequenceSeries_set(swigCPtr, value);
    } 
    get {
      short ret = CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_SequenceSeries_get(swigCPtr);
      return ret;
    } 
  }

  public int SequenceNo {
    set {
      CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_SequenceNo_set(swigCPtr, value);
    } 
    get {
      int ret = CTPTradeCppWrapperPINVOKE.CThostFtdcTradingNoticeInfoField_SequenceNo_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcTradingNoticeInfoField() : this(CTPTradeCppWrapperPINVOKE.new_CThostFtdcTradingNoticeInfoField(), true) {
  }

}
